Created models for JPA
StackScrubs/stuq pull request #4
Opened 2022-03-29 14:44 UTC by tomrsae

2022-03-29 17:00 UTC, norgor requested changes
Puuurty good job! 🦖  I commented on some small things 💯

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/controller/LoginController.java
> +@CrossOrigin(origins = "WRITE HOST HERE") //TODO:
Should read from an env var

2022-03-29 17:00 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Assignment.java
> +    public Assignment(int id, String name, Subject subject) {
add not null

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/LoginRequest.java
> +    }
add null-checking

2022-03-29 17:00 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/LoginResponse.java
> +@JsonInclude(JsonInclude.Include.NON_NULL)
Can't we use optional instead?

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Student.java
> +	}
not null here too? :)

2022-03-29 17:00 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Student.java
> +	}
not sure if you need it but the JPA not null thing :P

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Subject.java
> +    private Term term;
non nullable?

2022-03-29 17:00 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Submission.java
> +    public Submission(Student student, Assignment assignment, boolean is_approved, String feedback) {
use camelCase

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Submission.java
> +        this.feedback = feedback;
set correct nullability

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/Term.java
> +    private String period;
nullability! don't we need getters as well?

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/User.java
> +    }
non-nullable! 😄

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/service/LoginService.java
> +        // TODO!
todo 👍

2022-03-29 17:00 UTC, ngorke commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/service/LoginService.java
> +        // TODO!
an exception would be preferable, as then we know for sure we forgot to implement it

2022-03-29 17:00 UTC, tomrsae commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/controller/LoginController.java
> +@CrossOrigin(origins = "WRITE HOST HERE") //TODO:
Mapping too, or only origins?

2022-03-30 09:20 UTC, tomrsae reviewed
Make use of `this` consistent accross all files.

2022-03-30 11:17 UTC, norgor requested changes
R🧅

2022-03-30 11:17 UTC, ngorke commented on backend/.env
> +HOST=
can remove file

2022-03-30 11:17 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/jpa/Student.java
> +	}
these brackets are looking kind of unaligned

2022-03-30 11:17 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/jpa/SubjectId.java
> +        return result;
use Objects.hash

2022-03-30 11:17 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/jpa/SubmissionId.java
> +        return result;
Object.hash :)

2022-03-30 11:17 UTC, norgor commented on backend/src/main/java/com/github/stackscrubs/stuq/backend/model/jpa/TermId.java
> +        return result;
Object.hash

2022-03-30 13:58 UTC, norgor approved these changes
noice

2022-03-30 14:08 UTC, merged